### ISSUE TITLE
HITL with botpress-platform-webchat id error 

### ISSUE THREAD

**Issue by obirije** [botpress/botpress-hitl#6]
botpress-platform-webchat returns an id error when trying to chat from the human in the loop (HITL) module web UI

rror: Unhandled Rejection in Promise: Promise {
_bitField: 18087936,
_fulfillmentHandler0:
TypeError: Cannot read property 'id' of undefined
at _callee$ (C:\Users\user\botpress\node_modules\botpress-platform-webchat\bin\webpack:\src\socket.js:36:38)

**Comment by michaelulin** [comment]
+1

**Comment by snakecon** [comment]
Encounter the same problem.

**Comment by slvnperron** [comment]
Hey all, we fixed that issue recently. You can update your version of webchat to the latest and see if that works?

**Comment by maherma-adg** [comment]
The problem persist with current git version.

Searching for root cause of this error, I found bp.middlewares.sendOutgoing try to read DB using event.user.id

Looking into hitl source, I see this value is not set in the outgoing event.

I solve the problem inserting this line in src/index.js:136

         user: {id: session.userId},

I don't know if problem is on hitl, webchat or botpress, but this workaround solve my problem.

Regards,
Manuel
